#include "lang.h"

QMap<QString, QString> texts_en = {
    {"OR", "OR"},
    {"BTN_APP", "Apply"},
    {"BTN_DIS", "Discard"},
    {"BTN_CAN", "Cancel"},
    {"BTN_RES", "Reset"},
    {"USER_POST", "Posts"},
    {"USER_FOL", "Followers"},
    {"LINK", "Link"},
    {"NO_MDIA", "No media selected"},
    {"LOAD", "Loading…"},
    {"BTN_MGC", "Do Magic!"},
    {"BTN_DOWN", "Download"},
    {"BTN_SELC_DOWN", "Download selected"},
    {"BTN_SELC_ALL", "Select all"},
    {"BTN_SELC_NONE", "Deselect all"},
    {"MBR_MENU", "Menu"},
    {"MBR_MENU_SET", "Open settings…"},
    {"MBR_MENU_INFO", "Info"},
    {"NODE_TMSP", "Published on "},
    {"NODE_COM", "Comments have been restricted on this post."},
    {"NODE_LIKE", "Likes have been hidden on this post."},
    {"NODE_STRY_EXP", "Story expires on %1"},
    {"SET_TTL", "Settings"},
    {"SET_VER", "Version"},
    {"SET_LANG", "Language"},
    {"SET_TDF", "Download destination folder"},
    {"SET_BTN_RES", "Reset settings"},
    {"SET_BTN_APP", "Apply settings"},
    {"SET_CKBX_OFE", "Open file explorer when saving"},
    {"SET_CKBX_DQ", "Use Discord quoting format"},
    {"SET_CKBX_EAC", "Auto-copy text"},
    {"SET_CLOS", "There are unsaved changes. Would you like to save them?"},
    {"SET_CLOS2", "There are unsaved changes. Would you like to save them?\nThe application must be restarted for changes to take effect."},
    {"MV", "Media Viewer"},
    {"INFO_TTL", "Info"},
    {"INFO_RHEW", "Developed by rhewrani"},
    {"WARN_RL", "Please wait a moment before refreshing to avoid Instagram rate-limiting."},
    {"ERR_LINK_PROF", "Please enter a link to a post, reel, or story, not a profile."},
    {"ERR_LINK_INVL", "Invalid Instagram link"},
    {"ERR_LINK_INST", "Only Instagram links are supported."},
    {"ERR_FTCH_FAIL", "Failed to fetch data from the Instagram API: network error.\nThis may be due to Instagram rate-limiting. See log.txt for details."},
    {"NODE_COM2", "Disabled."},
    {"NODE_LIKE2", "Hidden."},
    {"YES", "Yes"},
    {"NO", "No"},
    {"SET_RSTT", "Are you sure you want to save these settings? The program has to be restarted in order for it to function correctly."},
    {"WARN_SIZE", "Discord only supports 10 attachments per message. The message would need to be split."},
    {"INFO_INST", "Limited functionality due to Instagram restrictions:\nInstagram imposes certain limitations that affect what content can be accessed through third-party tools. Specifically, without a valid session ID, the program cannot fetch Instagram Stories or posts marked as +18 (which includes some of Lisa’s posts). If you need access to this content, you can provide a valid session ID in the settings.\n\nThat being said, the program works fully and remains highly usable even without a session ID, and you’ll still be able to access most features without issue.\n\nEnjoy!"},
    {"ERR_FETCH_FAIL_POST", "Error extracting post data. This might be because +18 posts are only accessible with a session ID. Please see the \"Information\" tab or log.txt for more details."},
    {"ERR_FETCH_FAIL_STRY", "Error extracting story data. This might be because stories are only accessible with a session ID. Please see the \"Information\" tab or log.txt for more details."},
    {"INFO_COPY", "Generated Text copied! (Autocopy)"},
    {"INFO_NP", "Loading next page…"},
    {"LBL_LISA", "Hello Lisa"},
};

QMap<QString, QString> texts_de = {
    {"OR", "ODER"},
    {"BTN_APP", "Anwenden"},
    {"BTN_DIS", "Verwerfen"},
    {"BTN_CAN", "Abbrechen"},
    {"BTN_RES", "Zurücksetzen"},
    {"USER_POST", "Beiträge"},
    {"USER_FOL", "Follower"},
    {"LINK", "Link"},
    {"NO_MDIA", "Keine Medien ausgewählt"},
    {"LOAD", "Lädt…"},
    {"BTN_MGC", "Zauber!"},
    {"BTN_DOWN", "Herunterladen"},
    {"BTN_SELC_DOWN", "Ausgewählte herunterladen"},
    {"BTN_SELC_ALL", "Alle auswählen"},
    {"BTN_SELC_NONE", "Alle abwählen"},
    {"MBR_MENU", "Menü"},
    {"MBR_MENU_SET", "Einstellungen öffnen…"},
    {"MBR_MENU_INFO", "Informationen"},
    {"NODE_TMSP", "Veröffentlicht am "},
    {"NODE_COM", "Kommentare wurden für diesen Beitrag eingeschränkt."},
    {"NODE_LIKE", "Likes wurden für diesen Beitrag ausgeblendet."},
    {"NODE_STRY_EXP", "Story läuft am %1 ab"},
    {"SET_TTL", "Einstellungen"},
    {"SET_VER", "Version"},
    {"SET_LANG", "Sprache"},
    {"SET_TDF", "Zielordner für Downloads"},
    {"SET_BTN_RES", "Einstellungen zurücksetzen"},
    {"SET_BTN_APP", "Einstellungen anwenden"},
    {"SET_CKBX_OFE", "Datei-Explorer beim Speichern öffnen"},
    {"SET_CKBX_DQ", "Discord-Zitierformat verwenden"},
    {"SET_CKBX_EAC", "Text automatisch kopieren"},
    {"SET_CLOS", "Es gibt ungespeicherte Änderungen. Möchten Sie diese speichern?"},
    {"SET_CLOS2", "Es gibt ungespeicherte Änderungen. Möchten Sie diese speichern?\nDas Programm muss neu gestartet werden, damit die Änderungen wirksam werden."},
    {"MV", "Medienbetrachter"},
    {"INFO_TTL", "Informationen"},
    {"INFO_RHEW", "Entwickelt von rhewrani"},
    {"WARN_RL", "Bitte warten Sie einen Moment, bevor Sie die Seite aktualisieren, um Instagrams Rate-Limiting zu vermeiden."},
    {"ERR_LINK_PROF", "Bitte geben Sie einen Link zu einem Post, Reel oder einer Story ein, nicht zu einem Profil."},
    {"ERR_LINK_INVL", "Ungültiger Instagram-Link"},
    {"ERR_LINK_INST", "Nur Instagram-Links werden unterstützt."},
    {"ERR_FTCH_FAIL", "Die Daten konnten nicht von der Instagram-API abgerufen werden: Netzwerkfehler.\nDies kann an Instagrams Rate-Limiting liegen. Weitere Informationen finden Sie in der Datei log.txt."},
    {"NODE_COM2", "Deaktiviert."},
    {"NODE_LIKE2", "Ausgeblendet."},
    {"YES", "Ja"},
    {"NO", "Nein"},
    {"SET_RSTT", "Möchten Sie diese Einstellungen wirklich speichern? Das Programm muss neu gestartet werden, damit es korrekt funktioniert."},
    {"WARN_SIZE", "Discord unterstützt nur 10 Anhänge pro Nachricht. Die Nachricht müsste aufgeteilt werden."},
    {"INFO_INST", "Eingeschränkte Funktionen aufgrund von Instagram-Beschränkungen:\nInstagram erzwingt bestimmte Einschränkungen, die beeinflussen, welche Inhalte über Tools von Drittanbietern abgerufen werden können. Ohne eine gültige session ID kann das Programm weder Instagram-Stories noch Beiträge abrufen, die als +18 markiert sind (dazu gehören einige von Lisas Beiträgen). Wenn Sie Zugriff auf diese Inhalte benötigen, können Sie eine gültige session ID in den Einstellungen angeben.\n\nDas Programm funktioniert jedoch vollständig und bleibt auch ohne session ID sehr gut nutzbar. Die meisten Funktionen stehen Ihnen ohne Einschränkungen zur Verfügung.\n\nViel Spaß!"},
    {"ERR_FETCH_FAIL_POST", "Fehler beim Abrufen der Beitragsdaten. Dies kann daran liegen, dass +18-Beiträge nur mit einer gültigen session ID verfügbar sind. Weitere Informationen finden Sie im Reiter „Informationen“ oder in der Datei log.txt."},
    {"ERR_FETCH_FAIL_STRY", "Fehler beim Abrufen der Story-Daten. Dies kann daran liegen, dass Stories nur mit einer gültigen session ID verfügbar sind. Weitere Informationen finden Sie im Reiter „Informationen“ oder in der Datei log.txt."},
    {"INFO_COPY", "Generierter Text kopiert! (Autocopy)"},
    {"INFO_NP", "Lade nächste Seite…"},
    {"LBL_LISA", "Hallo Lisa"},

};

QMap<QString, QString> texts_da = {
    {"OR", "ELLER"},
    {"BTN_APP", "Anvend"},
    {"BTN_DIS", "Kassér"},
    {"BTN_CAN", "Annuller"},
    {"BTN_RES", "Nulstil"},
    {"USER_POST", "Indlæg"},
    {"USER_FOL", "Følgere"},
    {"LINK", "Link"},
    {"NO_MDIA", "Ingen medier valgt"},
    {"LOAD", "Indlæser…"},
    {"BTN_MGC", "Tryl!"},
    {"BTN_DOWN", "Download"},
    {"BTN_SELC_DOWN", "Download valgte"},
    {"BTN_SELC_ALL", "Vælg alle"},
    {"BTN_SELC_NONE", "Fravælg alle"},
    {"MBR_MENU", "Menu"},
    {"MBR_MENU_SET", "Åbn indstillinger…"},
    {"MBR_MENU_INFO", "Info"},
    {"NODE_TMSP", "Udgivet "},
    {"NODE_COM", "Kommentarer er begrænset på dette indlæg."},
    {"NODE_LIKE", "Likes er skjult på dette indlæg."},
    {"NODE_STRY_EXP", "Story udløber %1"},
    {"SET_TTL", "Indstillinger"},
    {"SET_VER", "Version"},
    {"SET_LANG", "Sprog"},
    {"SET_TDF", "Download-mappe"},
    {"SET_BTN_RES", "Nulstil indstillinger"},
    {"SET_BTN_APP", "Anvend indstillinger"},
    {"SET_CKBX_OFE", "Åbn filhåndtering ved gem"},
    {"SET_CKBX_DQ", "Brug Discord-citatformat"},
    {"SET_CKBX_EAC", "Kopiér tekst automatisk"},
    {"SET_CLOS", "Der er ikke-gemte ændringer. Vil du gemme dem?"},
    {"SET_CLOS2", "Der er ikke-gemte ændringer. Vil du gemme dem?\nProgrammet skal genstartes, før ændringerne træder i kraft."},
    {"MV", "Medieviser"},
    {"INFO_TTL", "Info"},
    {"INFO_RHEW", "Udviklet af rhewrani"},
    {"WARN_RL", "Vent venligst et øjeblik, før du genindlæser, for at undgå Instagrams rate-limiting."},
    {"ERR_LINK_PROF", "Indtast venligst et link til et indlæg, reel eller story – ikke et profil-link."},
    {"ERR_LINK_INVL", "Ugyldigt Instagram-link"},
    {"ERR_LINK_INST", "Kun Instagram-links understøttes."},
    {"ERR_FTCH_FAIL", "Kunne ikke hente data fra Instagram-API: netværksfejl.\nDette kan skyldes Instagrams rate-limiting. Se log.txt for yderligere oplysninger."},
    {"NODE_COM2", "Deaktiveret."},
    {"NODE_LIKE2", "Skjult."},
    {"YES", "Ja"},
    {"NO", "Nej"},
    {"SET_RSTT", "Er du sikker på, at du vil gemme disse indstillinger? Programmet skal genstartes for at fungere korrekt."},
    {"WARN_SIZE", "Discord understøtter kun 10 vedhæftede filer pr. besked. Beskeden skal deles op."},
    {"INFO_INST", "Begrænset funktionalitet på grund af Instagrams begrænsninger:\nInstagram pålægger visse begrænsninger, der påvirker, hvilket indhold der kan tilgås via tredjeparts-værktøjer. Specifikt kan programmet uden en gyldig session-ID ikke hente Instagram Stories eller indlæg markeret som +18 (hvilket inkluderer nogle af Lisas indlæg). Hvis du har brug for adgang til dette indhold, kan du angive en gyldig session-ID i indstillingerne.\n\nDet sagt, fungerer programmet fuldt ud og forbliver højt brugbart selv uden en session-ID, og du vil stadig kunne tilgå de fleste funktioner uden problemer.\n\nGod fornøjelse!"},
    {"ERR_FETCH_FAIL_POST", "Fejl under hentning af indlægsdata. Dette kan skyldes, at +18-indlæg kun er tilgængelige med en session-ID. Se fanebladet \"Information\" eller log.txt for yderligere detaljer."},
    {"ERR_FETCH_FAIL_STRY", "Fejl under hentning af story-data. Dette kan skyldes, at stories kun er tilgængelige med en session-ID. Se fanebladet \"Information\" eller log.txt for yderligere detaljer."},
    {"INFO_COPY", "Genereret tekst kopieret! (Autocopy)"},
    {"INFO_NP", "Indlæser næste side…"},
    {"LBL_LISA", "Hej Lisa"},

};

QMap<QString, QString> texts_nl = {
    {"OR", "OF"},
    {"BTN_APP", "Toepassen"},
    {"BTN_DIS", "Negeren"},
    {"BTN_CAN", "Annuleren"},
    {"BTN_RES", "Resetten"},
    {"USER_POST", "Posts"},
    {"USER_FOL", "Volgers"},
    {"LINK", "Link"},
    {"NO_MDIA", "Geen media geselecteerd"},
    {"LOAD", "Laden…"},
    {"BTN_MGC", "Tover!"},
    {"BTN_DOWN", "Downloaden"},
    {"BTN_SELC_DOWN", "Geselecteerde downloaden"},
    {"BTN_SELC_ALL", "Alles selecteren"},
    {"BTN_SELC_NONE", "Alles deselecteren"},
    {"MBR_MENU", "Menu"},
    {"MBR_MENU_SET", "Instellingen openen…"},
    {"MBR_MENU_INFO", "Informatie"},
    {"NODE_TMSP", "Gepubliceerd op "},
    {"NODE_COM", "Reacties zijn beperkt op deze post."},
    {"NODE_LIKE", "Likes zijn verborgen op deze post."},
    {"NODE_STRY_EXP", "Story verloopt op %1"},
    {"SET_TTL", "Instellingen"},
    {"SET_VER", "Versie"},
    {"SET_LANG", "Taal"},
    {"SET_TDF", "Downloadmap"},
    {"SET_BTN_RES", "Instellingen resetten"},
    {"SET_BTN_APP", "Instellingen toepassen"},
    {"SET_CKBX_OFE", "Bestandsverkenner openen bij opslaan"},
    {"SET_CKBX_DQ", "Discord-citaatopmaak gebruiken"},
    {"SET_CKBX_EAC", "Tekst automatisch kopiëren"},
    {"SET_CLOS", "Er zijn niet-opgeslagen wijzigingen. Wilt u ze opslaan?"},
    {"SET_CLOS2", "Er zijn niet-opgeslagen wijzigingen. Wilt u ze opslaan?\nDe applicatie moet opnieuw worden gestart om de wijzigingen toe te passen."},
    {"MV", "Mediaviewer"},
    {"INFO_TTL", "Informatie"},
    {"INFO_RHEW", "Ontwikkeld door rhewrani"},
    {"WARN_RL", "Wacht even voordat u vernieuwt om Instagram rate-limiting te voorkomen."},
    {"ERR_LINK_PROF", "Voer een link in naar een post, reel of story, niet naar een profiel."},
    {"ERR_LINK_INVL", "Ongeldige Instagram-link"},
    {"ERR_LINK_INST", "Alleen Instagram-links worden ondersteund."},
    {"ERR_FTCH_FAIL", "Kan gegevens niet ophalen van de Instagram-API: netwerkfout.\nDit kan komen door Instagram rate-limiting. Zie log.txt voor details."},
    {"NODE_COM2", "Uitgeschakeld."},
    {"NODE_LIKE2", "Verborgen."},
    {"YES", "Ja"},
    {"NO", "Nee"},
    {"SET_RSTT", "Weet u zeker dat u deze instellingen wilt opslaan? Het programma moet opnieuw worden gestart om correct te functioneren."},
    {"WARN_SIZE", "Discord ondersteunt slechts 10 bijlagen per bericht. Het bericht moet worden opgesplitst."},
    {"INFO_INST", "Beperkte functionaliteit vanwege Instagram-beperkingen:\nInstagram hanteert bepaalde beperkingen die van invloed zijn op welke inhoud via tools van derden toegankelijk is. Zonder een geldige session ID kan het programma geen Instagram-stories of +18-posts ophalen (waaronder sommige van Lisa’s posts). Als u toegang nodig hebt tot deze inhoud, kunt u een geldige session ID opgeven in de instellingen.\n\nDesondanks werkt het programma volledig en blijft het zeer bruikbaar, zelfs zonder session ID. De meeste functies zijn gewoon beschikbaar.\n\nVeel plezier!"},
    {"ERR_FETCH_FAIL_POST", "Fout bij het ophalen van postgegevens. Dit kan komen doordat +18-posts alleen toegankelijk zijn met een session ID. Zie het tabblad \"Informatie\" of log.txt voor meer informatie."},
    {"ERR_FETCH_FAIL_STRY", "Fout bij het ophalen van story-gegevens. Dit kan komen doordat stories alleen toegankelijk zijn met een session ID. Zie het tabblad \"Informatie\" of log.txt voor meer informatie."},
    {"INFO_COPY", "Gegenereerde tekst gekopieerd! (Autocopy)"},
    {"INFO_NP", "Volgende pagina laden…"},
    {"LBL_LISA", "Hallo Lisa"},

};

QMap<QString, QString> texts_fr = {
    {"OR", "OU"},
    {"BTN_APP", "Appliquer"},
    {"BTN_DIS", "Ignorer"},
    {"BTN_CAN", "Annuler"},
    {"BTN_RES", "Réinitialiser"},
    {"USER_POST", "Publications"},
    {"USER_FOL", "Abonnés"},
    {"LINK", "Lien"},
    {"NO_MDIA", "Aucun média sélectionné"},
    {"LOAD", "Chargement…"},
    {"BTN_MGC", "Magie!"},
    {"BTN_DOWN", "Télécharger"},
    {"BTN_SELC_DOWN", "Télécharger la sélection"},
    {"BTN_SELC_ALL", "Tout sélectionner"},
    {"BTN_SELC_NONE", "Tout désélectionner"},
    {"MBR_MENU", "Menu"},
    {"MBR_MENU_SET", "Ouvrir les paramètres…"},
    {"MBR_MENU_INFO", "Informations"},
    {"NODE_TMSP", "Publié le "},
    {"NODE_COM", "Les commentaires sont limités sur cette publication."},
    {"NODE_LIKE", "Les likes sont masqués sur cette publication."},
    {"NODE_STRY_EXP", "La story expire le %1"},
    {"SET_TTL", "Paramètres"},
    {"SET_VER", "Version"},
    {"SET_LANG", "Langue"},
    {"SET_TDF", "Dossier de téléchargement"},
    {"SET_BTN_RES", "Réinitialiser les paramètres"},
    {"SET_BTN_APP", "Appliquer les paramètres"},
    {"SET_CKBX_OFE", "Ouvrir l’explorateur de fichiers lors de l’enregistrement"},
    {"SET_CKBX_DQ", "Utiliser le format de citation Discord"},
    {"SET_CKBX_EAC", "Copier automatiquement le texte"},
    {"SET_CLOS", "Des modifications non enregistrées existent. Voulez-vous les enregistrer ?"},
    {"SET_CLOS2", "Des modifications non enregistrées existent. Voulez-vous les enregistrer ?\nL’application doit être redémarrée pour que les changements prennent effet."},
    {"MV", "Visionneuse multimédia"},
    {"INFO_TTL", "Informations"},
    {"INFO_RHEW", "Développé par rhewrani"},
    {"WARN_RL", "Veuillez patienter un instant avant de rafraîchir afin d’éviter la limitation de débit d’Instagram."},
    {"ERR_LINK_PROF", "Veuillez entrer un lien vers une publication, un Reel ou une story, pas vers un profil."},
    {"ERR_LINK_INVL", "Lien Instagram invalide"},
    {"ERR_LINK_INST", "Seuls les liens Instagram sont pris en charge."},
    {"ERR_FTCH_FAIL", "Échec de la récupération des données depuis l’API Instagram : erreur réseau.\nCela peut être dû à la limitation de débit d’Instagram. Consultez log.txt pour plus de détails."},
    {"NODE_COM2", "Désactivé."},
    {"NODE_LIKE2", "Masqué."},
    {"YES", "Oui"},
    {"NO", "Non"},
    {"SET_RSTT", "Voulez-vous vraiment enregistrer ces paramètres ? L’application doit être redémarrée pour fonctionner correctement."},
    {"WARN_SIZE", "Discord ne prend en charge que 10 pièces jointes par message. Le message devra être divisé."},
    {"INFO_INST", "Fonctionnalité limitée en raison des restrictions d’Instagram:\nInstagram applique certaines limitations qui affectent le contenu accessible via les outils tiers. Sans une session ID valide, le programme ne peut pas récupérer les Stories Instagram ni les publications marquées +18 (ce qui inclut certaines publications de Lisa). Si vous avez besoin d’accéder à ce contenu, vous pouvez fournir une session ID valide dans les paramètres.\n\nCela dit, le programme fonctionne pleinement et reste très utilisable même sans session ID, et vous pourrez toujours accéder à la majorité des fonctionnalités sans problème.\n\nAmusez-vous bien!"},
    {"ERR_FETCH_FAIL_POST", "Erreur lors de l’extraction des données de la publication. Cela peut être dû au fait que les publications +18 ne sont accessibles qu’avec une session ID. Veuillez consulter l’onglet « Informations » ou le fichier log.txt pour plus de détails."},
    {"ERR_FETCH_FAIL_STRY", "Erreur lors de l’extraction des données de la story. Cela peut être dû au fait que les stories ne sont accessibles qu’avec une session ID. Veuillez consulter l’onglet « Informations » ou le fichier log.txt pour plus de détails."},
    {"INFO_COPY", "Texte généré copié! (Autocopy)"},
    {"INFO_NP", "Chargement de la page suivante…"},
    {"LBL_LISA", "Bonjour Lisa"},

};

QMap<QString, QString> texts_es = {
    {"OR", "O"},
    {"BTN_APP", "Aplicar"},
    {"BTN_DIS", "Descartar"},
    {"BTN_CAN", "Cancelar"},
    {"BTN_RES", "Restablecer"},
    {"USER_POST", "Publicaciones"},
    {"USER_FOL", "Seguidores"},
    {"LINK", "Enlace"},
    {"NO_MDIA", "No se ha seleccionado ningún medio"},
    {"LOAD", "Cargando…"},
    {"BTN_MGC", "¡Magia!"},
    {"BTN_DOWN", "Descargar"},
    {"BTN_SELC_DOWN", "Descargar seleccionados"},
    {"BTN_SELC_ALL", "Seleccionar todo"},
    {"BTN_SELC_NONE", "Deseleccionar todo"},
    {"MBR_MENU", "Menú"},
    {"MBR_MENU_SET", "Abrir configuración…"},
    {"MBR_MENU_INFO", "Información"},
    {"NODE_TMSP", "Publicado el "},
    {"NODE_COM", "Los comentarios están limitados en esta publicación."},
    {"NODE_LIKE", "Los me gusta están ocultos en esta publicación."},
    {"NODE_STRY_EXP", "La historia caduca el %1"},
    {"SET_TTL", "Configuración"},
    {"SET_VER", "Versión"},
    {"SET_LANG", "Idioma"},
    {"SET_TDF", "Carpeta de descargas"},
    {"SET_BTN_RES", "Restablecer configuración"},
    {"SET_BTN_APP", "Aplicar configuración"},
    {"SET_CKBX_OFE", "Abrir el explorador de archivos al guardar"},
    {"SET_CKBX_DQ", "Usar formato de cita de Discord"},
    {"SET_CKBX_EAC", "Copiar texto automáticamente"},
    {"SET_CLOS", "Hay cambios sin guardar. ¿Desea guardarlos?"},
    {"SET_CLOS2", "Hay cambios sin guardar. ¿Desea guardarlos?\nDebe reiniciar la aplicación para que los cambios surtan efecto."},
    {"MV", "Visor multimedia"},
    {"INFO_TTL", "Información"},
    {"INFO_RHEW", "Desarrollado por rhewrani"},
    {"WARN_RL", "Espere un momento antes de actualizar para evitar el límite de solicitudes de Instagram."},
    {"ERR_LINK_PROF", "Introduzca un enlace a una publicación, Reel o historia, no a un perfil."},
    {"ERR_LINK_INVL", "Enlace de Instagram no válido"},
    {"ERR_LINK_INST", "Solo se admiten enlaces de Instagram."},
    {"ERR_FTCH_FAIL", "Error al obtener datos de la API de Instagram: error de red.\nEsto puede deberse al límite de solicitudes de Instagram. Consulte log.txt para más detalles."},
    {"NODE_COM2", "Desactivado."},
    {"NODE_LIKE2", "Oculto."},
    {"YES", "Sí"},
    {"NO", "No"},
    {"SET_RSTT", "¿Está seguro de que desea guardar esta configuración? Debe reiniciar el programa para que funcione correctamente."},
    {"WARN_SIZE", "Discord solo admite 10 archivos adjuntos por mensaje. El mensaje tendría que dividirse."},
    {"INFO_INST", "Funcionalidad limitada debido a las restricciones de Instagram:\nInstagram impone ciertas limitaciones que afectan al contenido accesible mediante herramientas de terceros. Específicamente, sin una session ID válida, el programa no puede obtener Stories de Instagram ni publicaciones marcadas como +18 (lo que incluye algunas publicaciones de Lisa). Si necesita acceder a este contenido, puede proporcionar una session ID válida en la configuración.\n\nDicho esto, el programa funciona completamente y sigue siendo muy usable incluso sin session ID, y podrá acceder a la mayoría de las funciones sin problemas.\n\n¡Disfrútelo!"},
    {"ERR_FETCH_FAIL_POST", "Error al extraer los datos de la publicación. Esto puede deberse a que las publicaciones +18 solo son accesibles con una session ID. Consulte la pestaña \"Información\" o el archivo log.txt para obtener más detalles."},
    {"ERR_FETCH_FAIL_STRY", "Error al extraer los datos de la story. Esto puede deberse a que las stories solo son accesibles con una session ID. Consulte la pestaña \"Información\" o el archivo log.txt para obtener más detalles."},
    {"INFO_COPY", "¡Texto generado copiado! (Autocopy)"},
    {"INFO_NP", "Cargando página siguiente…"},
    {"LBL_LISA", "Hola Lisa"},

};

QMap<QString, QString> texts_pt = {
    {"OR", "OU"},
    {"BTN_APP", "Aplicar"},
    {"BTN_DIS", "Descartar"},
    {"BTN_CAN", "Cancelar"},
    {"BTN_RES", "Repor"},
    {"USER_POST", "Publicações"},
    {"USER_FOL", "Seguidores"},
    {"LINK", "Link"},
    {"NO_MDIA", "Nenhum conteúdo selecionado"},
    {"LOAD", "A carregar…"},
    {"BTN_MGC", "Magia!"},
    {"BTN_DOWN", "Descarregar"},
    {"BTN_SELC_DOWN", "Descarregar selecionados"},
    {"BTN_SELC_ALL", "Selecionar tudo"},
    {"BTN_SELC_NONE", "Desmarcar tudo"},
    {"MBR_MENU", "Menu"},
    {"MBR_MENU_SET", "Abrir definições…"},
    {"MBR_MENU_INFO", "Informações"},
    {"NODE_TMSP", "Publicado em "},
    {"NODE_COM", "Os comentários estão limitados nesta publicação."},
    {"NODE_LIKE", "As curtidas estão ocultas nesta publicação."},
    {"NODE_STRY_EXP", "A story expira em %1"},
    {"SET_TTL", "Definições"},
    {"SET_VER", "Versão"},
    {"SET_LANG", "Idioma"},
    {"SET_TDF", "Pasta de destino para descargas"},
    {"SET_BTN_RES", "Repor definições"},
    {"SET_BTN_APP", "Aplicar definições"},
    {"SET_CKBX_OFE", "Abrir o explorador de ficheiros ao guardar"},
    {"SET_CKBX_DQ", "Utilizar formato de citação do Discord"},
    {"SET_CKBX_EAC", "Copiar texto automaticamente"},
    {"SET_CLOS", "Existem alterações não guardadas. Deseja guardá-las?"},
    {"SET_CLOS2", "Existem alterações não guardadas. Deseja guardá-las?\nA aplicação deve ser reiniciada para que as alterações tenham efeito."},
    {"MV", "Visualizador de conteúdos"},
    {"INFO_TTL", "Informações"},
    {"INFO_RHEW", "Desenvolvido por rhewrani"},
    {"WARN_RL", "Aguarde um momento antes de atualizar para evitar o rate-limiting do Instagram."},
    {"ERR_LINK_PROF", "Introduza um link para uma publicação, Reel ou story, não para um perfil."},
    {"ERR_LINK_INVL", "Link do Instagram inválido"},
    {"ERR_LINK_INST", "Apenas são suportados links do Instagram."},
    {"ERR_FTCH_FAIL", "Falha ao obter dados da API do Instagram: erro de rede.\nIsto pode dever-se ao rate-limiting do Instagram. Consulte log.txt para mais detalhes."},
    {"NODE_COM2", "Desativado."},
    {"NODE_LIKE2", "Oculto."},
    {"YES", "Sim"},
    {"NO", "Não"},
    {"SET_RSTT", "Tem a certeza de que pretende guardar estas definições? A aplicação tem de ser reiniciada para funcionar corretamente."},
    {"WARN_SIZE", "O Discord só suporta 10 anexos por mensagem. A mensagem terá de ser dividida."},
    {"INFO_INST", "Funcionalidade limitada devido às restrições do Instagram:\nO Instagram impõe certas limitações que afetam o conteúdo acessível por ferramentas de terceiros. Especificamente, sem um ID de sessão válido, o programa não pode buscar Stories do Instagram nem publicações marcadas como +18 (o que inclui algumas das publicações da Lisa). Se precisar de acesso a esse conteúdo, você pode fornecer um ID de sessão válido nas configurações.\n\nDito isso, o programa funciona perfeitamente e continua altamente utilizável mesmo sem um ID de sessão, e você ainda conseguirá acessar a maioria dos recursos sem problemas.\n\nAproveite!"},
    {"ERR_FETCH_FAIL_POST", "Erro ao extrair dados da publicação. Isso pode ocorrer porque publicações +18 só são acessíveis com um ID de sessão. Consulte a aba \"Informações\" ou o arquivo log.txt para mais detalhes."},
    {"ERR_FETCH_FAIL_STRY", "Erro ao extrair dados da story. Isso pode ocorrer porque as stories só são acessíveis com um ID de sessão. Consulte a aba \"Informações\" ou o arquivo log.txt para mais detalhes."},
    {"INFO_COPY", "Testo generato copiato! (Autocopy)"},
    {"INFO_NP", "A carregar página seguinte…"},
    {"LBL_LISA", "Olá Lisa"},

};

QMap<QString, QString> texts_it = {
    {"OR", "O"},
    {"BTN_APP", "Applica"},
    {"BTN_DIS", "Scarta"},
    {"BTN_CAN", "Annulla"},
    {"BTN_RES", "Reimposta"},
    {"USER_POST", "Post"},
    {"USER_FOL", "Follower"},
    {"LINK", "Link"},
    {"NO_MDIA", "Nessun media selezionato"},
    {"LOAD", "Caricamento…"},
    {"BTN_MGC", "Magia!"},
    {"BTN_DOWN", "Scarica"},
    {"BTN_SELC_DOWN", "Scarica selezionati"},
    {"BTN_SELC_ALL", "Seleziona tutto"},
    {"BTN_SELC_NONE", "Deseleziona tutto"},
    {"MBR_MENU", "Menu"},
    {"MBR_MENU_SET", "Apri impostazioni…"},
    {"MBR_MENU_INFO", "Informazioni"},
    {"NODE_TMSP", "Pubblicato il "},
    {"NODE_COM", "I commenti sono limitati su questo post."},
    {"NODE_LIKE", "I like sono nascosti su questo post."},
    {"NODE_STRY_EXP", "La storia scade il %1"},
    {"SET_TTL", "Impostazioni"},
    {"SET_VER", "Versione"},
    {"SET_LANG", "Lingua"},
    {"SET_TDF", "Cartella di destinazione per i download"},
    {"SET_BTN_RES", "Reimposta impostazioni"},
    {"SET_BTN_APP", "Applica impostazioni"},
    {"SET_CKBX_OFE", "Apri Esplora file al salvataggio"},
    {"SET_CKBX_DQ", "Usa il formato citazione di Discord"},
    {"SET_CKBX_EAC", "Copia automaticamente il testo"},
    {"SET_CLOS", "Ci sono modifiche non salvate. Vuoi salvarle?"},
    {"SET_CLOS2", "Ci sono modifiche non salvate. Vuoi salvarle?\nL'applicazione deve essere riavviata per rendere effettive le modifiche."},
    {"MV", "Visualizzatore multimediale"},
    {"INFO_TTL", "Informazioni"},
    {"INFO_RHEW", "Sviluppato da rhewrani"},
    {"WARN_RL", "Attendi un momento prima di aggiornare per evitare il rate-limiting di Instagram."},
    {"ERR_LINK_PROF", "Inserisci un link a un post, reel o storia, non a un profilo."},
    {"ERR_LINK_INVL", "Link Instagram non valido"},
    {"ERR_LINK_INST", "Sono supportati solo link di Instagram."},
    {"ERR_FTCH_FAIL", "Impossibile recuperare i dati dall'API di Instagram: errore di rete.\nCiò potrebbe essere dovuto al rate-limiting di Instagram. Consulta log.txt per ulteriori dettagli."},
    {"NODE_COM2", "Disabilitato."},
    {"NODE_LIKE2", "Nascosto."},
    {"YES", "Sì"},
    {"NO", "No"},
    {"SET_RSTT", "Vuoi davvero salvare queste impostazioni? L'applicazione deve essere riavviata per funzionare correttamente."},
    {"WARN_SIZE", "Discord supporta solo 10 allegati per messaggio. Il messaggio dovrà essere suddiviso."},
    {"INFO_INST", "Funzionalità limitata a causa delle restrizioni di Instagram:\nInstagram impone alcune limitazioni che influiscono sui contenuti accessibili tramite strumenti di terze parti. In particolare, senza una session ID valida, il programma non può recuperare le Storie di Instagram né i post contrassegnati come +18 (tra cui alcuni post di Lisa). Se hai bisogno di accedere a questo contenuto, puoi inserire una session ID valida nelle impostazioni.\n\nDetto questo, il programma funziona completamente e rimane molto utilizzabile anche senza session ID, e potrai comunque accedere alla maggior parte delle funzionalità senza problemi.\n\nBuon divertimento!"},
    {"ERR_FETCH_FAIL_POST", "Errore durante l’estrazione dei dati del post. Potrebbe essere perché i post +18 sono accessibili solo con una session ID. Consulta la scheda \"Informazioni\" o il file log.txt per ulteriori dettagli."},
    {"ERR_FETCH_FAIL_STRY", "Errore durante l’estrazione dei dati della storia. Potrebbe essere perché le storie sono accessibili solo con una session ID. Consulta la scheda \"Informazioni\" o il file log.txt per ulteriori dettagli."},
    {"INFO_COPY", "Texto gerado copiado! (Autocopy)"},
    {"INFO_NP", "Caricamento pagina successiva…"},
    {"LBL_LISA", "Ciao Lisa"},

};

QMap<QString, QString> texts_zh = {
    {"OR", "或"},
    {"BTN_APP", "应用"},
    {"BTN_DIS", "放弃"},
    {"BTN_CAN", "取消"},
    {"BTN_RES", "重置"},
    {"USER_POST", "帖子"},
    {"USER_FOL", "粉丝"},
    {"LINK", "链接"},
    {"NO_MDIA", "未选择任何媒体"},
    {"LOAD", "加载中…"},
    {"BTN_MGC", "魔法！"},
    {"BTN_DOWN", "下载"},
    {"BTN_SELC_DOWN", "下载所选内容"},
    {"BTN_SELC_ALL", "全选"},
    {"BTN_SELC_NONE", "取消全选"},
    {"MBR_MENU", "菜单"},
    {"MBR_MENU_SET", "打开设置…"},
    {"MBR_MENU_INFO", "信息"},
    {"NODE_TMSP", "发布于 "},
    {"NODE_COM", "此帖子的评论已被限制。"},
    {"NODE_LIKE", "此帖子的点赞数已隐藏。"},
    {"NODE_STRY_EXP", "故事将于 %1 过期"},
    {"SET_TTL", "设置"},
    {"SET_VER", "版本"},
    {"SET_LANG", "语言"},
    {"SET_TDF", "下载目标文件夹"},
    {"SET_BTN_RES", "重置设置"},
    {"SET_BTN_APP", "应用设置"},
    {"SET_CKBX_OFE", "保存时打开文件资源管理器"},
    {"SET_CKBX_DQ", "使用 Discord 引用格式"},
    {"SET_CKBX_EAC", "自动复制文本"},
    {"SET_CLOS", "存在未保存的更改。是否保存？"},
    {"SET_CLOS2", "存在未保存的更改。是否保存？\n必须重新启动程序才能使更改生效。"},
    {"MV", "媒体查看器"},
    {"INFO_TTL", "信息"},
    {"INFO_RHEW", "由 rhewrani 开发"},
    {"WARN_RL", "请稍等片刻再刷新，以避免触发 Instagram 的速率限制。"},
    {"ERR_LINK_PROF", "请输入帖子、Reel 或故事的链接，而非个人主页链接。"},
    {"ERR_LINK_INVL", "无效的 Instagram 链接"},
    {"ERR_LINK_INST", "仅支持 Instagram 链接。"},
    {"ERR_FTCH_FAIL", "无法从 Instagram API 获取数据：网络错误。\n这可能是由于 Instagram 的速率限制所致。详情请参阅 log.txt。"},
    {"NODE_COM2", "已禁用。"},
    {"NODE_LIKE2", "已隐藏。"},
    {"YES", "是"},
    {"NO", "否"},
    {"SET_RSTT", "您确定要保存这些设置吗？必须重新启动程序才能使其正常运行。"},
    {"WARN_SIZE", "Discord 每条消息最多只支持 10 个附件。该消息需要拆分发送。"},
    {"INFO_INST", "由于 Instagram 的限制，功能受限：\nInstagram 施加了某些限制，影响了第三方工具可访问的内容。具体来说，如果没有有效的会话 ID，程序无法获取 Instagram 快拍（Stories）或标记为 +18 的帖子（包括 Lisa 的部分帖子）。如果您需要访问这些内容，可以在设置中提供有效的会话 ID。\n\n尽管如此，即使没有会话 ID，程序也能完全运行且高度可用，您仍然可以毫无问题地使用大多数功能。\n\n祝您使用愉快！"},
    {"ERR_FETCH_FAIL_POST", "提取帖子数据时出错。这可能是因为 +18 帖子仅在提供会话 ID 时才可访问。请参阅“信息”选项卡或 log.txt 以获取更多详情。"},
    {"ERR_FETCH_FAIL_STRY", "提取快拍（story）数据时出错。这可能是因为快拍仅在提供会话 ID 时才可访问。请参阅“信息”选项卡或 log.txt 以获取更多详情。"},
    {"INFO_COPY", "已复制生成的文本！(Autocopy)"},
    {"INFO_NP", "正在加载下一页…"},
    {"LBL_LISA", "你好，Lisa"},
};

QMap<QString, QString> texts_jp = {
    {"OR", "または"},
    {"BTN_APP", "適用"},
    {"BTN_DIS", "破棄"},
    {"BTN_CAN", "キャンセル"},
    {"BTN_RES", "リセット"},
    {"USER_POST", "投稿"},
    {"USER_FOL", "フォロワー"},
    {"LINK", "リンク"},
    {"NO_MDIA", "メディアが選択されていません"},
    {"LOAD", "読み込み中…"},
    {"BTN_MGC", "マジック！"},
    {"BTN_DOWN", "ダウンロード"},
    {"BTN_SELC_DOWN", "選択したものをダウンロード"},
    {"BTN_SELC_ALL", "すべて選択"},
    {"BTN_SELC_NONE", "すべて選択解除"},
    {"MBR_MENU", "メニュー"},
    {"MBR_MENU_SET", "設定を開く…"},
    {"MBR_MENU_INFO", "情報"},
    {"NODE_TMSP", "公開日: "},
    {"NODE_COM", "この投稿のコメントは制限されています。"},
    {"NODE_LIKE", "この投稿の「いいね！」は非表示です。"},
    {"NODE_STRY_EXP", "ストーリーの有効期限: %1"},
    {"SET_TTL", "設定"},
    {"SET_VER", "バージョン"},
    {"SET_LANG", "言語"},
    {"SET_TDF", "ダウンロード先フォルダ"},
    {"SET_BTN_RES", "設定をリセット"},
    {"SET_BTN_APP", "設定を適用"},
    {"SET_CKBX_OFE", "保存時にファイルエクスプローラーを開く"},
    {"SET_CKBX_DQ", "Discord 引用形式を使用"},
    {"SET_CKBX_EAC", "テキストを自動コピー"},
    {"SET_CLOS", "保存されていない変更があります。保存しますか？"},
    {"SET_CLOS2", "保存されていない変更があります。保存しますか？\n変更を反映するにはアプリを再起動する必要があります。"},
    {"MV", "メディアビューア"},
    {"INFO_TTL", "情報"},
    {"INFO_RHEW", "開発者: rhewrani"},
    {"WARN_RL", "Instagram のレート制限を回避するため、更新する前に少し待ってください。"},
    {"ERR_LINK_PROF", "プロフィールではなく、投稿、リール、またはストーリーのリンクを入力してください。"},
    {"ERR_LINK_INVL", "無効な Instagram リンクです"},
    {"ERR_LINK_INST", "Instagram リンクのみ対応しています。"},
    {"ERR_FTCH_FAIL", "Instagram API からデータを取得できませんでした: ネットワークエラー。\nこれは Instagram のレート制限が原因の可能性があります。詳細は log.txt を確認してください。"},
    {"NODE_COM2", "無効化されています。"},
    {"NODE_LIKE2", "非表示です。"},
    {"YES", "はい"},
    {"NO", "いいえ"},
    {"SET_RSTT", "これらの設定を保存してもよろしいですか？正しく機能させるには、プログラムを再起動する必要があります。"},
    {"WARN_SIZE", "Discord は1メッセージにつき10個までの添付ファイルしかサポートしていません。メッセージを分割する必要があります。"},
    {"INFO_INST", "Instagramの制限により機能が制限されています：\nInstagramは第三者ツールによるコンテンツへのアクセスにいくつかの制限を設けています。具体的には、有効なセッションIDがない場合、Instagramのストーリーや+18とマークされた投稿（Lisaの投稿の一部を含む）を取得できません。これらのコンテンツにアクセスする必要がある場合は、設定で有効なセッションIDを提供してください。\n\nただし、セッションIDがなくてもプログラムは完全に動作し、ほとんどの機能を問題なく利用できます。\n\nお楽しみください！"},
    {"ERR_FETCH_FAIL_POST", "投稿データの取得中にエラーが発生しました。これは、+18の投稿がセッションIDでのみアクセス可能であるためかもしれません。「情報」タブまたはlog.txtを確認してください。"},
    {"ERR_FETCH_FAIL_STRY", "ストーリーデータの取得中にエラーが発生しました。これは、ストーリーがセッションIDでのみアクセス可能であるためかもしれません。「情報」タブまたはlog.txtを確認してください。"},
    {"INFO_COPY", "生成されたテキストをコピーしました！(Autocopy)"},
    {"INFO_NP", "次のページを読み込み中…"},
    {"LBL_LISA", "こんにちは、Lisa"},
};

QMap<QString, QString> texts_kr = {
    {"OR", "또는"},
    {"BTN_APP", "적용"},
    {"BTN_DIS", "취소"},
    {"BTN_CAN", "닫기"},
    {"BTN_RES", "초기화"},
    {"USER_POST", "게시물"},
    {"USER_FOL", "팔로워"},
    {"LINK", "링크"},
    {"NO_MDIA", "미디어가 선택되지 않았습니다"},
    {"LOAD", "로드 중…"},
    {"BTN_MGC", "마법!"},
    {"BTN_DOWN", "다운로드"},
    {"BTN_SELC_DOWN", "선택 항목 다운로드"},
    {"BTN_SELC_ALL", "모두 선택"},
    {"BTN_SELC_NONE", "선택 해제"},
    {"MBR_MENU", "메뉴"},
    {"MBR_MENU_SET", "설정 열기…"},
    {"MBR_MENU_INFO", "정보"},
    {"NODE_TMSP", "게시일: "},
    {"NODE_COM", "이 게시물의 댓글이 제한되었습니다."},
    {"NODE_LIKE", "이 게시물의 좋아요가 숨겨졌습니다."},
    {"NODE_STRY_EXP", "스토리 만료일: %1"},
    {"SET_TTL", "설정"},
    {"SET_VER", "버전"},
    {"SET_LANG", "언어"},
    {"SET_TDF", "다운로드 폴더"},
    {"SET_BTN_RES", "설정 초기화"},
    {"SET_BTN_APP", "설정 적용"},
    {"SET_CKBX_OFE", "저장 시 파일 탐색기 열기"},
    {"SET_CKBX_DQ", "Discord 인용 형식 사용"},
    {"SET_CKBX_EAC", "텍스트 자동 복사"},
    {"SET_CLOS", "저장하지 않은 변경 사항이 있습니다. 저장하시겠습니까?"},
    {"SET_CLOS2", "저장하지 않은 변경 사항이 있습니다. 저장하시겠습니까?\n변경 사항을 적용하려면 프로그램을 다시 시작해야 합니다."},
    {"MV", "미디어 뷰어"},
    {"INFO_TTL", "정보"},
    {"INFO_RHEW", "rhewrani 개발"},
    {"WARN_RL", "Instagram의 요청 제한을 피하려면 새로 고치기 전에 잠시 기다려 주세요."},
    {"ERR_LINK_PROF", "프로필이 아닌 게시물, 리얼 또는 스토리의 링크를 입력하세요."},
    {"ERR_LINK_INVL", "잘못된 Instagram 링크입니다"},
    {"ERR_LINK_INST", "Instagram 링크만 지원됩니다."},
    {"ERR_FTCH_FAIL", "Instagram API에서 데이터를 가져오지 못했습니다: 네트워크 오류.\nInstagram의 요청 제한 때문일 수 있습니다. 자세한 내용은 log.txt를 확인하세요."},
    {"NODE_COM2", "비활성화됨."},
    {"NODE_LIKE2", "숨겨짐."},
    {"YES", "예"},
    {"NO", "아니요"},
    {"SET_RSTT", "이 설정을 저장하시겠습니까? 프로그램이 올바르게 작동하려면 재시작해야 합니다."},
    {"WARN_SIZE", "Discord는 메시지당 최대 10개의 첨부 파일만 지원합니다. 메시지를 분할해야 합니다."},
    {"INFO_INST", "Instagram 제한으로 인해 기능이 제한됩니다:\nInstagram은 제3자 도구를 통해 접근 가능한 콘텐츠에 일부 제한을 두고 있습니다. 특히 유효한 세션 ID 없이는 Instagram 스토리나 +18로 표시된 게시물(Lisa의 일부 게시물을 포함함)을 가져올 수 없습니다. 해당 콘텐츠에 접근이 필요하시면 설정에서 유효한 세션 ID를 입력해 주세요.\n\n그럼에도 불구하고, 세션 ID 없이도 프로그램은 완전히 작동하며 대부분의 기능을 문제없이 사용하실 수 있습니다.\n\n즐기세요!"},
    {"ERR_FETCH_FAIL_POST", "게시물 데이터 추출 중 오류가 발생했습니다. 이는 +18 게시물이 세션 ID가 있어야만 접근 가능하기 때문일 수 있습니다. 자세한 내용은 '정보' 탭 또는 log.txt를 참조하세요."},
    {"ERR_FETCH_FAIL_STRY", "스토리 데이터 추출 중 오류가 발생했습니다. 이는 스토리가 세션 ID가 있어야만 접근 가능하기 때문일 수 있습니다. 자세한 내용은 '정보' 탭 또는 log.txt를 참조하세요."},
    {"INFO_COPY", "생성된 텍스트를 복사했습니다! (Autocopy)"},
    {"INFO_NP", "다음 페이지 로드 중…"},
    {"LBL_LISA", "안녕, Lisa"},
};


QMap<QString, QString> texts_th = {
    {"OR", "หรือ"},
    {"BTN_APP", "นำไปใช้"},
    {"BTN_DIS", "ยกเลิก"},
    {"BTN_CAN", "ยกเลิก"},
    {"BTN_RES", "รีเซ็ต"},
    {"USER_POST", "โพสต์"},
    {"USER_FOL", "ผู้ติดตาม"},
    {"LINK", "ลิงก์"},
    {"NO_MDIA", "ไม่ได้เลือกสื่อใดๆ"},
    {"LOAD", "กำลังโหลด…"},
    {"BTN_MGC", "เสกคาถา!"},
    {"BTN_DOWN", "ดาวน์โหลด"},
    {"BTN_SELC_DOWN", "ดาวน์โหลดที่เลือก"},
    {"BTN_SELC_ALL", "เลือกทั้งหมด"},
    {"BTN_SELC_NONE", "ไม่เลือกทั้งหมด"},
    {"MBR_MENU", "เมนู"},
    {"MBR_MENU_SET", "เปิดการตั้งค่า…"},
    {"MBR_MENU_INFO", "ข้อมูล"},
    {"NODE_TMSP", "โพสต์เมื่อ "},
    {"NODE_COM", "ความคิดเห็นถูกจำกัดในโพสต์นี้"},
    {"NODE_LIKE", "ไลก์ถูกซ่อนในโพสต์นี้"},
    {"NODE_STRY_EXP", "สตอรี่หมดอายุ %1"},
    {"SET_TTL", "การตั้งค่า"},
    {"SET_VER", "เวอร์ชัน"},
    {"SET_LANG", "ภาษา"},
    {"SET_TDF", "โฟลเดอร์ปลายทางสำหรับดาวน์โหลด"},
    {"SET_BTN_RES", "รีเซ็ตการตั้งค่า"},
    {"SET_BTN_APP", "นำไปใช้กับการตั้งค่า"},
    {"SET_CKBX_OFE", "เปิด File Explorer เมื่อบันทึก"},
    {"SET_CKBX_DQ", "ใช้รูปแบบการอ้างอิงของ Discord"},
    {"SET_CKBX_EAC", "คัดลอกข้อความอัตโนมัติ"},
    {"SET_CLOS", "มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก คุณต้องการบันทึกหรือไม่?"},
    {"SET_CLOS2", "มีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก คุณต้องการบันทึกหรือไม่?\nคุณต้องรีสตาร์ทโปรแกรมเพื่อให้การเปลี่ยนแปลงมีผล"},
    {"MV", "ตัวแสดงสื่อ"},
    {"INFO_TTL", "ข้อมูล"},
    {"INFO_RHEW", "พัฒนาโดย rhewrani"},
    {"WARN_RL", "กรุณารอสักครู่ก่อนรีเฟรช เพื่อหลีกเลี่ยงการถูกจำกัดอัตราการร้องขอจาก Instagram"},
    {"ERR_LINK_PROF", "กรุณาใส่ลิงก์โพสต์ Reel หรือสตอรี่ ไม่ใช่ลิงก์โปรไฟล์"},
    {"ERR_LINK_INVL", "ลิงก์ Instagram ไม่ถูกต้อง"},
    {"ERR_LINK_INST", "รองรับเฉพาะลิงก์ Instagram เท่านั้น"},
    {"ERR_FTCH_FAIL", "ไม่สามารถดึงข้อมูลจาก API ของ Instagram ได้: ข้อผิดพลาดเครือข่าย\nอาจเกิดจากการจำกัดอัตราการร้องขอของ Instagram ดูรายละเอียดเพิ่มเติมใน log.txt"},
    {"NODE_COM2", "ปิดใช้งานแล้ว"},
    {"NODE_LIKE2", "ซ่อนอยู่"},
    {"YES", "ใช่"},
    {"NO", "ไม่"},
    {"SET_RSTT", "คุณแน่ใจหรือว่าต้องการบันทึกการตั้งค่าเหล่านี้? คุณต้องรีสตาร์ทโปรแกรมเพื่อให้ทำงานได้อย่างถูกต้อง"},
    {"WARN_SIZE", "Discord รองรับไฟล์แนบได้สูงสุด 10 ไฟล์ต่อข้อความเท่านั้น ข้อความนี้จำเป็นต้องถูกแบ่งออก"},
    {"INFO_INST", "ฟังก์ชันถูกจำกัดเนื่องจากข้อจำกัดของ Instagram:\nInstagram ได้กำหนดข้อจำกัดบางอย่างที่ส่งผลต่อเนื้อหาที่สามารถเข้าถึงได้ผ่านเครื่องมือภายนอก โดยเฉพาะอย่างยิ่ง หากไม่มี Session ID ที่ถูกต้อง โปรแกรมจะไม่สามารถดึงข้อมูล Instagram Stories หรือโพสต์ที่ถูกทำเครื่องหมายว่า +18 (ซึ่งรวมถึงโพสต์บางส่วนของ Lisa) ได้ หากคุณต้องการเข้าถึงเนื้อหานี้ คุณสามารถระบุ Session ID ที่ถูกต้องในส่วนการตั้งค่าได้\n\nอย่างไรก็ตาม โปรแกรมยังคงทำงานได้อย่างสมบูรณ์และใช้งานได้ดีมากแม้ไม่มี Session ID และคุณจะยังคงสามารถเข้าถึงฟีเจอร์ส่วนใหญ่ได้โดยไม่มีปัญหา\n\nขอให้สนุก!"},
    {"ERR_FETCH_FAIL_POST", "เกิดข้อผิดพลาดขณะดึงข้อมูลโพสต์ อาจเป็นเพราะโพสต์ที่มีเรต +18 สามารถเข้าถึงได้เฉพาะเมื่อมี Session ID เท่านั้น โปรดดูที่แท็บ \"ข้อมูล\" หรือไฟล์ log.txt สำหรับรายละเอียดเพิ่มเติม"},
    {"ERR_FETCH_FAIL_STRY", "เกิดข้อผิดพลาดขณะดึงข้อมูลสตอรี่ อาจเป็นเพราะสตอรี่สามารถเข้าถึงได้เฉพาะเมื่อมี Session ID เท่านั้น โปรดดูที่แท็บ \"ข้อมูล\" หรือไฟล์ log.txt สำหรับรายละเอียดเพิ่มเติม"},
    {"INFO_COPY", "คัดลอกข้อความที่สร้างแล้ว! (Autocopy)"},
    {"INFO_NP", "กำลังโหลดหน้าถัดไป…"},
    {"LBL_LISA", "สวัสดี Lisa"},
};

